# Generated by Django 5.0.6 on 2024-06-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_client_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact_person',
        ),
    ]
