# Generated by Django 5.0.6 on 2024-06-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_client_contact_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
