# Generated by Django 5.0.6 on 2024-06-09 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Planning', 'Planning'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=50, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.builder')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.client')),
            ],
        ),
    ]
